apiVersion: v1
kind: Service
metadata:
  name: go-demo-2
spec:
  type: NodePort
  ports:
  - port: 28017 # Find the pods on port 28017
    nodePort: 30001 # Let service expose a specified port
    protocol: TCP
  selector:
    type: backend
    service: go-demo-2